### ISSUE TITLE
Project 3 deadline typo

### ISSUE THREAD

**Issue by jam53** [RubenVerborgh/WebFundamentals#103]
When looking to the [Overview and modalities](https://github.ugent.be/pages/WebDevelopment/About/#practical-sessions) slides, the deadline for the 3th project is stated as May 20th 2023. According to Ufora however, the deadline would be on May 26th 2023 (see the picture attached).

Since all of the deadlines fall on a Friday, and May 20th is on a Saturday; I assume that this is the deadline from 2022 which was inadvertently overlooked when updating the slides. Could you please confirm whether or not this is the case, or what the correct deadline is?

Thanks in advance!

![image](https://user-images.githubusercontent.com/47756749/219706753-39f72eca-ff34-4d47-a0d8-0a917fcf237b.png)

I made an attempt at creating a pull request to fix this typo. However, I wasn't able to find the slide in question within the repository, hence the issue.

**Comment by RubenVerborgh** [comment]
@rubensworks?

**Comment by rubensworks** [comment]
Deadline should be on a Friday indeed (May 19). Will update on the slides and Ufora right away.
Thanks for noticing @jam53!
