### ISSUE TITLE
Make an overview of all the chapters/lessons

### ISSUE THREAD

**Issue by mglanghe** [RubenVerborgh/WebFundamentals#15]
It would be handy to navigate between the different chapters.
This would also make it faster to find something.
Now there's no easy way (to my knowledge) to go to lesson 2.

**Comment by RubenVerborgh** [comment]
Hi @mglanghe, that's right!

I only created a navigation path from the [introductory slides](http://rubenverborgh.github.io/WebFundamentals/#index) to the other lectures, but that's just one way in which people might want to browse it. (Kind of like how the [Europeana API assumes you will always follow a certain path](http://rubenverborgh.github.io/WebFundamentals/web-apis/#europeana-api).)

It would be great to have each lecture link to the next and previous ones. Perhaps an additional slide at the end, or navigation links at the top of the slide overview.

Any takers? :wink:

**Comment by RubenVerborgh** [comment]
I've added links to the top of each overview page. Hope this helps. If not, don't hesitate to reopen.
