### ISSUE TITLE
"Tim" =/= "Tim"@en

### ISSUE THREAD

**Issue by mielvds** [RubenVerborgh/WebFundamentals#16]
This was probably a pragmatic, for the sake of simplicity, choice, but since semantics are important here, I would avoid it.

https://github.com/RubenVerborgh/WebFundamentals/blob/gh-pages/semantic-web/index.html#L640
claims the "Tim" is Tim with a language tag "en", but it isn't. I know, I'm nit picking :)

**Comment by RubenVerborgh** [comment]
You're right. I'd probably change it in the diagram itself, so that it really depicts the English-language version of the name.
