### ISSUE TITLE
Have the spacebar work to scroll down the page

### ISSUE THREAD

**Issue by pollecuttn** [RubenVerborgh/WebFundamentals#18]
Very low priority!

Looking at http://rubenverborgh.github.io/WebFundamentals/semantic-web/#recap I can't scroll down by using the space bar (as I usually expect to do on a web page).

Can this be fixed so the space bar works as usual for a web page to scroll down?

Thanks!

**Comment by RubenVerborgh** [comment]
This can definitely be fixed (will need to be in the Shower framework). Shower now absorbs all keypresses, I think.

**Comment by Dromin** [comment]
It would also be nice if we could use the mouse scrolling wheel to navigate the slides (like you can do in PowerPoint, for example).

**Comment by RubenVerborgh** [comment]
@pollecuttn Actually, it seems that Shower reconfigures the space bar to scroll down one slide at a time in overview mode (verified in Chrome 48 on OS X). Do you also observe this?

@Dromin You mean, when in full-screen mode, that scrolling brings you to the next slide? That certainly seems handy.

**Comment by Dromin** [comment]
More specifically, scrolling down would bring you to the next step in the current slide (for instance, if there are multiple list items that are displayed one by one), or to the next slide if there isn't a next step in the current slide. Scrolling up would do this in reverse (e.g. make list items invisible one by one, then go to previous slide).

**Comment by RubenVerborgh** [comment]
@Dromin That make sense. Unfortunately, it's not as straightforward as it seems. I did some quick fiddling yesterday, and making the slides react to scroll movements itself is pretty easy. The trouble, however, is in knowing what _one_ scroll movement exactly is. Many touchpads these days have scrolling inertia, i.e., after you stop the scrolling movement, the object continues scrolling a little. So I was sliding down and depending on how fast I did it, either 1 item or 27 slides scrolled by (and getting that 1 item consistently was very hard).

I've read a couple of [discussions](https://github.com/jquery/jquery-mousewheel/issues/36) on this, and perhaps [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling) can be the solution. I'll need to investigate this some more at a later time, and will try to make it into a pull request for [Shower](https://github.com/shower/shower) (same for the spacebar). I also plan on improving touch for mobile.

**Comment by pollecuttn** [comment]
@RubenVerborgh I'm afraid I don't know what overview mode is. I'd be happy to test if you send me a link (I'm on Windows and Chrome 48)

**Comment by RubenVerborgh** [comment]
@pollecuttn You can either view the slides full-screen (presentation mode), or see a list of slides (overview mode). To go from full-screen to overview mode, press the escape button. You now see a list of slides. What happens if you press the spacebar?

**Comment by pollecuttn** [comment]
@RubenVerborgh Okay, I now see what you mean about the scroll bar reconfiguring the space bar to scroll down one slide at a time in overview mode. It took me a few goes to see that's what was happening because it isn't what I expect when hitting the space bar on a web page (I expect the whole page to move down). I guess also because it's not scrolling down, it's just moving on one slide and what you see in the viewport doesn't change/move on.

So yes, I am seeing that. But only when it's been explained to me. It  feels like it's broken a web convention to me (or broken what I conventionally expect on the web).

**Comment by RubenVerborgh** [comment]
@pollecuttn I can agree on that (though I'm not a spacebar user myself). I'll make a pull request with the Shower framework, pointing to this discussion.

**Comment by pollecuttn** [comment]
@RubenVerborgh Many thanks!

**Comment by RubenVerborgh** [comment]
The pull request has been merged in Shower (https://github.com/shower/core/pull/29#event-590881049), I'll update Shower in these slides when its next version is released.

**Comment by pepelsbey** [comment]
Fixed in shower-core 2.0.5 (and shower 2.0.8)

**Comment by RubenVerborgh** [comment]
Great, thanks for merging and releasing!

**Comment by pollecuttn** [comment]
Many thanks to everyone for fixing this so promptly.
