### ISSUE TITLE
Niet-intuitieve structuur van de repo

### ISSUE THREAD

**Issue by MaartenDesnouck** [RubenVerborgh/WebFundamentals#2]
De 'Finding your way around' sectie is handig maar ik vind het handiger als ik naar de bestanden kijk en het direct snap. Vb 'architecture' en 'scripts', welke map is inhoud en welke is functioneel? Mogelijk oplossing daarvoor is volgens mij de bestandsstructuur om te keren en bv in de root de mappen 'slideshtml', 'images', 'scripts', ... te hebben en dan in die mappen onderverdelingen te maken per hoofdstuk. Of... en dit is minder werk: een map 'slides' in de root directory met daarin 'architecture', 'birds-eye-view',...

**Comment by RubenVerborgh** [comment]
Dag @Desnouck,

Dankjewel voor dit issue! Je haalt inderdaad een probleem aan, dat mogelijk een aantal mensen ontmoedigt om met de slides te beginnen. Ik vorige week al opgevangen dat velen het niet duidelijk vonden waar te beginnen, en daarom [schreef](https://github.com/RubenVerborgh/WebFundamentals/commit/43538a9a87f8aa710069ca88824f3b3902ba7cd5) ik alvast de [“Finding your way around”](https://github.com/RubenVerborgh/WebFundamentals#finding-your-way-around).

Nog beter dan zo'n infosectie zou natuurlijk zijn dat de structuur geen uitleg behoeft :smile:

De enige beperking waar ik mee zit is dat de GitHub pages server een [gewone fileserver](http://rubenverborgh.github.io/WebFundamentals/architecture/#file-server) is, en dat er een directe koppeling bestaat tussen de bestandsnamen en de URLs. Dat betekent dus dat de keuze voor het bestandssysteem (helaas) ook een weerslag heeft op de URL-structuur – en die wil ik natuurlijk zo proper mogelijk houden. Laat ons even zien wat de mogelijkheden zijn.

### Optie 1: slides verplaatsen

Een naam zoals `slides` zou steek kunnen houden. Dan wordt dit bijvoorbeeld `http://rubenverborgh.github.io/WebFundamentals/slides/architecture/`. Dit geeft dan ook ruimte om later andere materialen te plaatsen dan slides.

Het enige nadeel echter is dat ik, als ik de slides verplaats, nog steeds compatibiliteit moet voorzien om de vermijden dat mijn bestaande URLs breken. Dus in de praktijk zouden er dan toch nog mapjes moeten blijven bestaan met redirects, om de oude URLs te kunnen blijven ondersteunen. (Groot nadeel van een statische fileserver. Ik kan me niet echt permitteren als web-advocaat om URLs te breken, zie je :wink:)

### Optie 2: andere content verplaatsen

Zou het helpen mochten de andere mappen verplaatst worden? Bijvoorbeeld, mocht ik deze namen geven als `_scripts`, `_styles`, `_images`? Op die manier staan ze apart van de content. Hun locatie kan ik eenvoudig veranderen, omdat ik alle links daarheen kan aanpassen. Een andere optie zou zijn om al de huidige mappen met hulpbestanden in één folder `_assets` of zo te plaatsen.

### Optie 3: symlinks

Een ander idee zou zijn om alles te laten staan, maar symbolische links te maken voor eenvoudige toegang. Dan zou ik bijvoorbeeld een mapje kunnen maken `_SLIDES_` (dat dan bovenaan gesorteerd wordt) met daarin symlinks naar `architecture` etc.

---

Wat denk je van deze opties? Zie je er nog meer? Betrek gerust ook anderen in de discussie, kwestie van een aantal meningen te hebben.

**Comment by MaartenDesnouck** [comment]
Optie 2 met alle hulpbestanden in _assets lijkt mij de beste.

**Comment by RubenVerborgh** [comment]
Lijkt me ook niet slecht. Ga hem misschien `_shared` noemen om te benadrukken dat die assets gedeeld worden door alle slides (naast de `images` folder die iedere les heeft).

**Comment by RubenVerborgh** [comment]
Voilà, hopelijk maakt dit de repo meer toegankelijk!
