### ISSUE TITLE
Semantic Web: Add examples of how and when to use RDF syntaxes (Turtle/JSON-LD etc.)

### ISSUE THREAD

**Issue by Dromin** [RubenVerborgh/WebFundamentals#20]
It currently isn't clear from the slides what the practical use of RDF and its different syntaxes is. Examples would make this more clear.

**Comment by RubenVerborgh** [comment]
True. In the structure of the slides, I wanted to introduce Linked Data (concept + datasets) before the RDF theory comes. However, this means that when the datasets are mentioned, RDF has not been explained yet, so it's too early to already show RDF.

Probably the datasets can be revisited after RDF is introduced. As in, the Linked Data section mentions the available data, and in the RDF part, we look at how that data is concretely accessible.

**Comment by RubenVerborgh** [comment]
4da669c0b58575503145fa8f64f3a65e0b296ca5 explains where RDF can be found. To fully address this issue, however, the [_Linked Data on the Web_ section](http://rubenverborgh.github.io/WebFundamentals/semantic-web/#linked-data-web) needs some rethinking (#30).

For 2015–2016, these slides are to be considered together with the _Metadata_ lecture, which details a couple of use cases for RDF. Together, they sketch a pretty complete picture. For 2016–2017, it might be best if we move those examples to _Linked Data on the Web_.

**Comment by RubenVerborgh** [comment]
Following up on this in #30.
