### ISSUE TITLE
Semantic Web: Add info about RDFa

### ISSUE THREAD

**Issue by Dromin** [RubenVerborgh/WebFundamentals#21]
Because [RDFa](https://en.wikipedia.org/wiki/RDFa) is currently preferred by Google over JSON-LD as a way to add (schema.org) metadata to existing (X)HTML pages ([source](https://developers.google.com/structured-data/schema-org)), I think it might be useful to add a (or a few) slides about RDFa and how to use it (for example how to get a rich snippet for a product page).

**Comment by RubenVerborgh** [comment]
Truth be told, I really forgot adding RDFa as concrete RDF syntax, hence I'm labelling this as “bug”.

Slides on this need to be added; the [schema](http://rubenverborgh.github.io/WebFundamentals/semantic-web/#rdf-syntaxes-schema) might need to be extended with something like “standalone syntaxes” and “embedded syntaxes”. In any case, RDFa needs to receive explanation, plus also a discussion of whether to create an all-in-one representation (HTML + RDFa) or separate representations with content negotiation (HTML, JSON-LD, …).
