### ISSUE TITLE
Voldoet JSON aan REST constraints?

### ISSUE THREAD

**Issue by lmicverm** [RubenVerborgh/WebFundamentals#32]
De vraag hoort voornamelijk bij deze slide:
http://rubenverborgh.github.io/WebFundamentals/web-apis/#web-hateoas

In het hoofdstuk over web api's worden de constraints besproken om aan een unfiforme interface te voldoen. O.a. verschillende representaties en hypermedia zijn er 2 van. Verschillende representaties kunnen dus JSON en html zijn. Verder wordt er ook gezegd dat hypermedia bestaat uit o.a. links en dan worden 2 voorbeelden gegeven van links:

`<em>http://perdu.com/</em>` (geen link)
`<a href="http://perdu.com/">Perdu</a>` (wel een link)

Nu maak ik hier uit op dat men dus enkel over links spreekt indien men er op kan klikken en dus niet indien ze bv in plaintext staan.

Mijn vraag is of er dan wel kan gezegd worden dat een resource in JSON voldoet aan de REST constraints, aangezien de links die hier worden meegestuurd altijd in string notatie zijn en ze dus ook niet clickable zijn waardoor er dus niet voldaan is aan de constraint van hypermedia.
Alvast bedankt.

**Comment by RubenVerborgh** [comment]
> Nu maak ik hier uit op dat men dus enkel over links spreekt indien men er op kan klikken en dus niet indien ze bv in plaintext staan.

Iets preciezer: we spreken enkel over een link als die interpretatie toegelaten is door het media-type.  (In het geval van HTML volgt daaruit dat je erop kan klikken, maar lang niet alle media-types hebben die functionaliteit.)

Dus uit het voorbeeld:

``` HTML
<em>http://perdu.com/</em> (geen link)
<a href="http://perdu.com/">Perdu</a> (wel een link)
```

Als we de [`em`-tag opzoeken in de HTML-specificatie](https://www.w3.org/TR/html5/text-level-semantics.html#the-em-element), zien we:

> > The `em` element represents stress emphasis of its contents.

Als we de [`a`-tag opzoeken](https://www.w3.org/TR/html5/text-level-semantics.html#the-a-element), zien we:

> > If the `a` element has an `href` attribute, then it represents a hyperlink (a hypertext anchor) labeled by its contents.

Dus enkel in dit laatste geval hebben we een hyperlink.

---

> Mijn vraag is of er dan wel kan gezegd worden dat een resource in JSON voldoet aan de REST constraints, aangezien de links die hier worden meegestuurd altijd in string notatie zijn

Da's een zeer scherpe opmerking.

Inderdaad, een gewoon JSON-document laat de interpretatie als een link niet toe.  Dus met het media-type `application/json` kan je strikt gezien geen hypermedia-applicaties bouwen.

Daarom bestaan er subtypes van application/json, die wel zo'n interpretatie hebben.  Een voorbeeld van zo'n subtype is [JSON-LD](http://rubenverborgh.github.io/WebFundamentals/semantic-web/#jsonld), dat als MIME-type application/ld+json heeft.  Hoewel URLs niet “klikbaar” zijn, mogen ze [volgens JSON-LD](https://www.w3.org/TR/json-ld/#iris) wel degelijk als hyperlinks geïnterpreteerd worden:

> > A string is interpreted as an IRI when it is the value of an `@id` member

Meer over het gebrek aan hyperlinks in JSON (en hoe JSON-LD een oplossing is) kan je [hier](https://www.w3.org/TR/json-ld/#basic-concepts) lezen.  Er bestaan ook andere formaten, zoals [HAL](http://stateless.co/hal_specification.html), die JSON uitbreiden met hypermedia.

Merk op dat dit strikt gezien betekent dat we in practicum 1 en 2 een extra interpretatie aan de JSON-data toevoegen, die eigenlijk verder gaat dan wat de spec toelaat. Om volledig correct te zijn, zouden we een specifieke media-type moeten gebruiken.

---

### Oplossing

Om dit duidelijk te maken in de cursus, stel ik voor om een slide toe te voegen na http://rubenverborgh.github.io/WebFundamentals/web-apis/#web-hateoas die dit duidelijk maakt voor andere formaten.

#### huidige slides
- [_HTML (and other hypermedia) documents can contain hypermedia controls._](http://rubenverborgh.github.io/WebFundamentals/web-apis/#web-hateoas)
- [hypertext definition](http://rubenverborgh.github.io/WebFundamentals/web-apis/#hypertext-definition)

#### aangepaste slides
- [_HTML documents can contain hypermedia controls._](http://rubenverborgh.github.io/WebFundamentals/web-apis/#web-hateoas)
  - explain why the interpretation as hypermedia is allowed
- [hypertext definition](http://rubenverborgh.github.io/WebFundamentals/web-apis/#hypertext-definition)
- _Hypermedia controls can appear in other documents with an appropriate media type._
  - explain why regular JSON does not allow a hypermedia interpretation
  - explain why some subtypes do allow a hypermedia interpretation
