### ISSUE TITLE
Problem YouTube video "The Internet's Own Boy" 

### ISSUE THREAD

**Issue by mglanghe** [RubenVerborgh/WebFundamentals#35]
In the part "A Bird's-Eye View of the Web" the YouTube video "The Internet's Own Boy" has been removed because of copyright claims. Ironic, isn't it? There are however other copies of the video on YouTube (e.g. https://www.youtube.com/watch?v=9vz06QO3UkQ).

**Comment by RubenVerborgh** [comment]
Thanks for reporting! Not only ironic, but strange, because the movie was released under a Creative Commons license. So I'm not sure what copyright claims any party could make. Will replace.
