### ISSUE TITLE
Semantic Web: add information about ontologies such as FOAF

### ISSUE THREAD

**Issue by Dromin** [RubenVerborgh/WebFundamentals#36]
One thing I found confusing while I was studying this course was that in the Semantic Web chapter prefixes such as 'foaf' are used quite a lot but it is (as far as I remember) never explained what they are referring to. Maybe this information could be added to the chapter?

**Comment by RubenVerborgh** [comment]
Thanks for the feedback—a slide with all the prefixes would definitely be good.
