### ISSUE TITLE
Web architecture: clarification of URL abbreviation

### ISSUE THREAD

**Issue by domien96** [RubenVerborgh/WebFundamentals#40]
I found it a bit unexpected that the U stands for Uniform instead of Unique, because throughout the whole explanation one talks about uniqueness.

**Comment by RubenVerborgh** [comment]
That's a good remark indeed: the “unique” aspect is silently assumed when saying “identifier” (i.e., if it didn't uniquely point at one thing, it wouldn't really be an identifier). The “uniform” aspect relates to the fact that all URIs have the same shape at the macro level (scheme, authority, path, query, fragment).

It would be good to integrate the above explanation in the slide. If you or anyone else has a suggestion, let me know!

**Comment by domien96** [comment]
As you suggested, adding this information in (or after) [this slide](http://rubenverborgh.github.io/WebFundamentals/architecture/#url-family) because it already contains information about the other keywords of 'URL' seems the clearest option to me.
