### ISSUE TITLE
Chart meaning 

### ISSUE THREAD

**Issue by lekova** [RubenVerborgh/WebFundamentals#55]
I am a little bit fuzzy on what does the chart represent on the business slide http://rubenverborgh.github.io/WebFundamentals/birds-eye-view/#business. Maybe adding a legend with the colors and x and y axis labels would make it easier to read and understand. 10x

**Comment by RubenVerborgh** [comment]
Indeed! The graphs was left without axis labels because there are multiple interpretations (and thus axes) possible, but it's probably most instructional to stick to one interpretation and make it explicit.

**Comment by RubenVerborgh** [comment]
What do you think about the new version, @lekova?
